### PR TITLE
Update: new post demo session picostack 

### PR DESCRIPTION
**Pull request by dpaez**
This PR adds a new entry post introducing our upcoming demo sessions. Starting with picostack.

**Update**

- Video embed added to the post with many last-minute UX tweaks.
- Post is almost ready to be published:
  - to-do: make the demo session public on youtube prior to merge this. Just that.
- tweet about it!

/cc @ninabreznik

### CODE REVIEW

**Comment by ninabreznik** [comment]
@dpaez It looks great! I will work on preparing a template for the intro and will make the first one for Tony soon so I can then add it to the video, upload it and give you the correct video link :)

**Comment by ninabreznik** [comment]
@dpaez I prepared the demo video. It is uploaded to the Dat ecosystem Youtube (it is private for now, so we need to make it public once we publish the blog post and announce the AMA)

**Comment by ninabreznik** [comment]
@dpaez I haven't managed to check yet, but I guess you mention the AMA/Comm comm call and when that will be. Probabky our tweet shoukd focus on mentioning the call + link to full post.

I will be at the CCCamp this week so back on Sunday!

**Comment by dpaez** [comment]
@ninabreznik I was thinking to introduce the AMA via twitter and discord. Since scheduling details can change. Also I'd prefer to launch this post first announce it and then announce the AMA with Tony in the 1st week of September, day/time to be confirmed.

**Comment by ninabreznik** [comment]
@dpaez would we publish all demos one after another eaxh week and then after that do the AMA's?

Just so we have a rollout plan and we kniw exactly what is coming out when.

**Comment by dpaez** [comment]
@ninabreznik I was thinking more doing 1 demo post - 1 AMA (to maintain some time coherence, eg this week its all about PicoStack, next Hop, next....). Also, we don't know if all projects would be doing AMAs, but for sure they would have a demo post.
🤔

**Comment by ninabreznik** [comment]
@dpaez yes, I was thinking the same. But how much gap would we have between the post and the ama session. I was thinking we do it a week after the post.

Dang, I realized it is late august already, so technically if we publish it next week, we t÷, have the ama in spetember. Geeez. Is this what you had in mind?

**Comment by dpaez** [comment]
I'm OK to post this next week. Like Monday 21 would be fine. I'm already working on the next article. 
We can always re-scheduled something if needed. Maybe at some point we can leave a week pass in between post and AMA if makes, like a middle break/recap.

**Comment by ninabreznik** [comment]
@dpaez sounda like a plan. I think what is good if we stick to some sort of rythem is that people then learn the pattern and kniw what to expect. So let's decide for some pattern and try to do always more or less same days and same gaps in between.

I was posting interviews on Tuesdays (and 2x Wednesday, because Kayla was running a bit late). I was also checking the views on Youtube and noticed people were clicking mire towards the end of the week. But I posted Tuesday/Wednesday and then boosted on Thursday/Friday.

I don't want to sound too anal about this. It is just that in this regular rythm there is also some poetry so this why I find it nice. It is somw predictability for the community as well.

**Comment by dpaez** [comment]
@ninabreznik AMA session info added. Ready to go.

**Comment by ninabreznik** [comment]
Awesome. Let's go then. Should we publish Sunday afternoon EU time (then
everyone is relaxed, not busy at work and can see the post) + afternoon in
the EU is then morning at your place and late evening in Asia so we kind of
cover all the places...

If you need any help or info from my side let me know, otherwise just
publish and let the party begin 🔥

**Pull request merged**
